#!/bin/sh

# monitors
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of DisplayPort-0

# autostart
nitrogen --restore &
blueman-applet &
picom --no-fading-openclose &

## make sure that Java apps can reparent and show anything
wmname LG3D

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

## start emacs server
systemctl --user start emacs


# Set some bsp specific stuff
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

# panel
pkill polybar
polybar top &
polybar top2 &

nm-applet & # network applet

bspc config window_gap 0
bspc config border_width 2
bspc config top_padding -5
bspc config left_padding 0
bspc config rigth padding 0
#bspc config top_monocle_padding 0

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config single_monocle true
#bspc config top_monocle_padding 30
#bspc config bottom_monocle_padding 0
#bspc config right_monocle_padding 0
#bspc confgi left_monocle_padding 0


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# always launch emacs in tiling
bspc rule -a Emacs state=tiled

## and peek in floating
bspc rule -a peek state=floating


